In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import os
from pprint import pprint
import json
from sqlalchemy import create_engine, Column, Integer, String, Float
from sqlalchemy.ext.declarative import declarative_base

In [2]:
# Create URL string
url = "https://ssd-api.jpl.nasa.gov/fireball.api?"
query = "date-min=2021-01-01&req-alt=true"
response = requests.get(url + query)

In [3]:
#Get response
data = response.json()
pprint(data)

{'count': '30',
 'data': [['2022-01-11 03:33:13',
           '126.4',
           '2.9',
           '58.4',
           'S',
           '160.2',
           'W',
           '40.8',
           '22.8'],
          ['2022-01-01 20:23:04',
           '14.5',
           '0.42',
           '66.1',
           'N',
           '152.6',
           'W',
           '35.5',
           None],
          ['2021-12-29 03:15:35',
           '2.0',
           '0.073',
           '69.7',
           'S',
           '115.0',
           'E',
           '44',
           '22.0'],
          ['2021-12-23 21:27:58',
           '2.1',
           '0.076',
           '4.9',
           'S',
           '29.6',
           'W',
           '37',
           None],
          ['2021-12-20 23:15:55',
           '3.2',
           '0.11',
           '62.7',
           'N',
           '60.3',
           'E',
           '56',
           '18.2'],
          ['2021-12-10 01:19:06',
           '5.0',
           '0.16',
           '47.5',
           'S',
           '172.6',
           'E',
           '27.5',
           None],
          ['2021-11-28 18:06:50',
           '4.0',
           '0.13',
           '32.6',
           'N',
           '113.5',
           'E',
           '38.4',
           '19.7'],
          ['2021-11-17 15:53:21',
           '2.4',
           '0.086',
           '6.8',
           'S',
           '119.1',
           'E',
           '35.0',
           '23.0'],
          ['2021-11-08 05:28:28',
           '3.3',
           '0.11',
           '33.8',
           'S',
           '7.7',
           'W',
           '36',
           None],
          ['2021-10-28 09:10:30',
           '3.0',
           '0.1',
           '4.1',
           'S',
           '138.7',
           'W',
           '35.2',
           None],
          ['2021-10-21 10:32:02',
           '3.7',
           '0.13',
           '51.5',
           'N',
           '51.4',
           'E',
           '30',
           '15.9'],
          ['2021-10-20 08:41:50',
           '6.0',
           '0.19',
           '13.8',
           'N',
           '140.4',
           'W',
           '28',
           None],
          ['2021-10-20 00:43:57',
           '2.0',
           '0.073',
           '59.0',
           'N',
           '154.3',
           'E',
           '31.4',
           '27.5'],
          ['2021-09-29 10:50:59',
           '13.7',
           '0.4',
           '53.9',
           'N',
           '148.0',
           'W',
           '28.0',
           '21.2'],
          ['2021-09-06 17:55:42',
           '3.1',
           '0.11',
           '2.1',
           'S',
           '111.8',
           'W',
           '26.0',
           '13.6'],
          ['2021-07-30 08:06:34',
           '14.6',
           '0.42',
           '7.8',
           'S',
           '90.1',
           'E',
           '63.0',
           None],
          ['2021-07-29 13:19:57',
           '3.7',
           '0.13',
           '42.4',
           'N',
           '98.4',
           'E',
           '26.4',
           '14.7'],
          ['2021-07-05 03:46:24',
           '74',
           '1.8',
           '44.3',
           'N',
           '164.2',
           'W',
           '43.4',
           '15.7'],
          ['2021-05-16 15:51:08',
           '3.8',
           '0.13',
           '52.1',
           'S',
           '171.2',
           'W',
           '37.0',
           None],
          ['2021-05-06 05:54:27',
           '2.1',
           '0.076',
           '34.7',
           'S',
           '141.0',
           'E',
           '31.0',
           '26.6'],
          ['2021-04-13 02:16:47',
           '2.1',
           '0.076',
           '26.8',
           'N',
           '79.1',
           'W',
           '44.4',
           '14.1'],
          ['2021-04-02 15:52:58',
           '13.7',
           '0.4',
           '71.2',
           'N',
           '106.7',
           'E',
           '40.0',
           None],
          ['2021-03-06 08:43:06',
           '14.1',
           '0.41',
           '48.6',
           'S',
           '90.4',
           'E',
           '31.1',
           None],
          ['2021-03-05 13:50:01',
           '3.9',
           '0.13',
           '81.1',
           'S',
           '141.1',
           'E',
           '32.5',
           None],
          ['2021-02-09 23:27:29',
           '3.0',
           '0.1',
           '75.8',
           'N',
           '92.8',
           'W',
           '31.0',
           None],
          ['2021-02-02 10:03:21',
           '3.1',
           '0.11',
           '48.7',
           'N',
           '80.1',
           'E',
           '20',
           None],
          ['2021-01-31 02:59:39',
           '26.7',
           '0.72',
           '5.3',
           'N',
           '115.2',
           'E',
           '39.4',
           None],
          ['2021-01-29 16:12:47',
           '7.7',
           '0.24',
           '38.8',
           'N',
           '51.3',
           'W',
           '30.0',
           None],
          ['2021-01-25 03:01:37',
           '7.5',
           '0.23',
           '38.5',
           'N',
           '47.6',
           'W',
           '19.1',
           None],
          ['2021-01-24 07:33:43',
           '6.1',
           '0.2',
           '45.0',
           'S',
           '95.5',
           'E',
           '37.5',
           None]],
 'fields': ['date',
            'energy',
            'impact-e',
            'lat',
            'lat-dir',
            'lon',
            'lon-dir',
            'alt',
            'vel'],
 'signature': {'source': 'NASA/JPL Fireball Data API', 'version': '1.0'}}

In [4]:
# Assign data a variable
fire_ball = data['data']
fire_ball

[['2022-01-11 03:33:13',
  '126.4',
  '2.9',
  '58.4',
  'S',
  '160.2',
  'W',
  '40.8',
  '22.8'],
 ['2022-01-01 20:23:04',
  '14.5',
  '0.42',
  '66.1',
  'N',
  '152.6',
  'W',
  '35.5',
  None],
 ['2021-12-29 03:15:35',
  '2.0',
  '0.073',
  '69.7',
  'S',
  '115.0',
  'E',
  '44',
  '22.0'],
 ['2021-12-23 21:27:58', '2.1', '0.076', '4.9', 'S', '29.6', 'W', '37', None],
 ['2021-12-20 23:15:55',
  '3.2',
  '0.11',
  '62.7',
  'N',
  '60.3',
  'E',
  '56',
  '18.2'],
 ['2021-12-10 01:19:06',
  '5.0',
  '0.16',
  '47.5',
  'S',
  '172.6',
  'E',
  '27.5',
  None],
 ['2021-11-28 18:06:50',
  '4.0',
  '0.13',
  '32.6',
  'N',
  '113.5',
  'E',
  '38.4',
  '19.7'],
 ['2021-11-17 15:53:21',
  '2.4',
  '0.086',
  '6.8',
  'S',
  '119.1',
  'E',
  '35.0',
  '23.0'],
 ['2021-11-08 05:28:28', '3.3', '0.11', '33.8', 'S', '7.7', 'W', '36', None],
 ['2021-10-28 09:10:30', '3.0', '0.1', '4.1', 'S', '138.7', 'W', '35.2', None],
 ['2021-10-21 10:32:02',
  '3.7',
  '0.13',
  '51.5',
  'N',
  '51.4',
  'E',
  '30',
  '15.9'],
 ['2021-10-20 08:41:50', '6.0', '0.19', '13.8', 'N', '140.4', 'W', '28', None],
 ['2021-10-20 00:43:57',
  '2.0',
  '0.073',
  '59.0',
  'N',
  '154.3',
  'E',
  '31.4',
  '27.5'],
 ['2021-09-29 10:50:59',
  '13.7',
  '0.4',
  '53.9',
  'N',
  '148.0',
  'W',
  '28.0',
  '21.2'],
 ['2021-09-06 17:55:42',
  '3.1',
  '0.11',
  '2.1',
  'S',
  '111.8',
  'W',
  '26.0',
  '13.6'],
 ['2021-07-30 08:06:34',
  '14.6',
  '0.42',
  '7.8',
  'S',
  '90.1',
  'E',
  '63.0',
  None],
 ['2021-07-29 13:19:57',
  '3.7',
  '0.13',
  '42.4',
  'N',
  '98.4',
  'E',
  '26.4',
  '14.7'],
 ['2021-07-05 03:46:24',
  '74',
  '1.8',
  '44.3',
  'N',
  '164.2',
  'W',
  '43.4',
  '15.7'],
 ['2021-05-16 15:51:08',
  '3.8',
  '0.13',
  '52.1',
  'S',
  '171.2',
  'W',
  '37.0',
  None],
 ['2021-05-06 05:54:27',
  '2.1',
  '0.076',
  '34.7',
  'S',
  '141.0',
  'E',
  '31.0',
  '26.6'],
 ['2021-04-13 02:16:47',
  '2.1',
  '0.076',
  '26.8',
  'N',
  '79.1',
  'W',
  '44.4',
  '14.1'],
 ['2021-04-02 15:52:58',
  '13.7',
  '0.4',
  '71.2',
  'N',
  '106.7',
  'E',
  '40.0',
  None],
 ['2021-03-06 08:43:06',
  '14.1',
  '0.41',
  '48.6',
  'S',
  '90.4',
  'E',
  '31.1',
  None],
 ['2021-03-05 13:50:01',
  '3.9',
  '0.13',
  '81.1',
  'S',
  '141.1',
  'E',
  '32.5',
  None],
 ['2021-02-09 23:27:29', '3.0', '0.1', '75.8', 'N', '92.8', 'W', '31.0', None],
 ['2021-02-02 10:03:21', '3.1', '0.11', '48.7', 'N', '80.1', 'E', '20', None],
 ['2021-01-31 02:59:39',
  '26.7',
  '0.72',
  '5.3',
  'N',
  '115.2',
  'E',
  '39.4',
  None],
 ['2021-01-29 16:12:47',
  '7.7',
  '0.24',
  '38.8',
  'N',
  '51.3',
  'W',
  '30.0',
  None],
 ['2021-01-25 03:01:37',
  '7.5',
  '0.23',
  '38.5',
  'N',
  '47.6',
  'W',
  '19.1',
  None],
 ['2021-01-24 07:33:43', '6.1', '0.2', '45.0', 'S', '95.5', 'E', '37.5', None]]

In [5]:
# Create pandas dataframe
fire_ball_data = pd.DataFrame(fire_ball)
fire_ball_data.head()

                     0      1      2     3  4      5  6     7     8
0  2022-01-11 03:33:13  126.4    2.9  58.4  S  160.2  W  40.8  22.8
1  2022-01-01 20:23:04   14.5   0.42  66.1  N  152.6  W  35.5  None
2  2021-12-29 03:15:35    2.0  0.073  69.7  S  115.0  E    44  22.0
3  2021-12-23 21:27:58    2.1  0.076   4.9  S   29.6  W    37  None
4  2021-12-20 23:15:55    3.2   0.11  62.7  N   60.3  E    56  18.2

In [6]:
# rename columns
fire_ball_data.rename(columns = {0:'date', 
                                1: 'energy', 
                                2: 'impactenergy', 
                                3: 'latitude', 
                                4: 'latdirection', 
                                5: 'longitude', 
                                6: 'londirection', 
                                7: 'altitude_km', 
                                8: 'velocity_kms'
                                }, inplace = True)
fire_ball_data.head()

,date,energy,impactenergy,latitude,latdirection,longitude,londirection,altitude_km,velocity_kms
0,2022-01-11 03:33:13,126.4,2.9,58.4,S,160.2,W,40.8,22.8
1,2022-01-01 20:23:04,14.5,0.42,66.1,N,152.6,W,35.5,None
2,2021-12-29 03:15:35,2.0,0.073,69.7,S,115.0,E,44,22.0
3,2021-12-23 21:27:58,2.1,0.076,4.9,S,29.6,W,37,None
4,2021-12-20 23:15:55,3.2,0.11,62.7,N,60.3,E,56,18.2

In [7]:
# insert placeholder column for 'time'
fire_ball_data['time'] = ""
fire_ball_data.head()

,date,energy,impactenergy,latitude,latdirection,longitude,londirection,altitude_km,velocity_kms,time
0,2022-01-11 03:33:13,126.4,2.9,58.4,S,160.2,W,40.8,22.8,
1,2022-01-01 20:23:04,14.5,0.42,66.1,N,152.6,W,35.5,None,
2,2021-12-29 03:15:35,2.0,0.073,69.7,S,115.0,E,44,22.0,
3,2021-12-23 21:27:58,2.1,0.076,4.9,S,29.6,W,37,None,
4,2021-12-20 23:15:55,3.2,0.11,62.7,N,60.3,E,56,18.2,

In [8]:
fire_ball_data

,date,energy,impactenergy,latitude,latdirection,longitude,londirection,altitude_km,velocity_kms,time
0,2022-01-11 03:33:13,126.4,2.9,58.4,S,160.2,W,40.8,22.8,
1,2022-01-01 20:23:04,14.5,0.42,66.1,N,152.6,W,35.5,None,
2,2021-12-29 03:15:35,2.0,0.073,69.7,S,115.0,E,44,22.0,
3,2021-12-23 21:27:58,2.1,0.076,4.9,S,29.6,W,37,None,
4,2021-12-20 23:15:55,3.2,0.11,62.7,N,60.3,E,56,18.2,
5,2021-12-10 01:19:06,5.0,0.16,47.5,S,172.6,E,27.5,None,
6,2021-11-28 18:06:50,4.0,0.13,32.6,N,113.5,E,38.4,19.7,
7,2021-11-17 15:53:21,2.4,0.086,6.8,S,119.1,E,35.0,23.0,
8,2021-11-08 05:28:28,3.3,0.11,33.8,S,7.7,W,36,None,
9,2021-10-28 09:10:30,3.0,0.1,4.1,S,138.7,W,35.2,None,
10,2021-10-21 10:32:02,3.7,0.13,51.5,N,51.4,E,30,15.9,
11,2021-10-20 08:41:50,6.0,0.19,13.8,N,140.4,W,28,None,
12,2021-10-20 00:43:57,2.0,0.073,59.0,N,154.3,E,31.4,27.5,
13,2021-09-29 10:50:59,13.7,0.4,53.9,N,148.0,W,28.0,21.2,
14,2021-09-06 17:55:42,3.1,0.11,2.1,S,111.8,W,26.0,13.6,
15,2021-07-30 08:06:34,14.6,0.42,7.8,S,90.1,E,63.0,None,
16,2021-07-29 13:19:57,3.7,0.13,42.4,N,98.4,E,26.4,14.7,
17,2021-07-05 03:46:24,74,1.8,44.3,N,164.2,W,43.4,15.7,
18,2021-05-16 15:51:08,3.8,0.13,52.1,S,171.2,W,37.0,None,
19,2021-05-06 05:54:27,2.1,0.076,34.7,S,141.0,E,31.0,26.6,
20,2021-04-13 02:16:47,2.1,0.076,26.8,N,79.1,W,44.4,14.1,
21,2021-04-02 15:52:58,13.7,0.4,71.2,N,106.7,E,40.0,None,
22,2021-03-06 08:43:06,14.1,0.41,48.6,S,90.4,E,31.1,None,
23,2021-03-05 13:50:01,3.9,0.13,81.1,S,141.1,E,32.5,None,
24,2021-02-09 23:27:29,3.0,0.1,75.8,N,92.8,W,31.0,None,
25,2021-02-02 10:03:21,3.1,0.11,48.7,N,80.1,E,20,None,
26,2021-01-31 02:59:39,26.7,0.72,5.3,N,115.2,E,39.4,None,
27,2021-01-29 16:12:47,7.7,0.24,38.8,N,51.3,W,30.0,None,
28,2021-01-25 03:01:37,7.5,0.23,38.5,N,47.6,W,19.1,None,
29,2021-01-24 07:33:43,6.1,0.2,45.0,S,95.5,E,37.5,None,

In [9]:
#reorder columns
fire_ball_data = fire_ball_data.reindex(columns = ['date', 
                                                   'time', 
                                                   'energy', 
                                                   'impactenergy', 
                                                   'latitude', 
                                                   'latdirection', 
                                                   'longitude', 
                                                   'londirection', 
                                                   'altitude_km', 
                                                   'velocity_kms'
                                                  ])
fire_ball_data.head()

,date,time,energy,impactenergy,latitude,latdirection,longitude,londirection,altitude_km,velocity_kms
0,2022-01-11 03:33:13,,126.4,2.9,58.4,S,160.2,W,40.8,22.8
1,2022-01-01 20:23:04,,14.5,0.42,66.1,N,152.6,W,35.5,None
2,2021-12-29 03:15:35,,2.0,0.073,69.7,S,115.0,E,44,22.0
3,2021-12-23 21:27:58,,2.1,0.076,4.9,S,29.6,W,37,None
4,2021-12-20 23:15:55,,3.2,0.11,62.7,N,60.3,E,56,18.2

In [10]:
# split date and time into seperate columns
fire_ball_data['date'] = pd.to_datetime(fire_ball_data['date'])

fire_ball_data = fire_ball_data.assign(date=fire_ball_data.date.dt.date, time=fire_ball_data.date.dt.time)

In [11]:
fire_ball_data

,date,time,energy,impactenergy,latitude,latdirection,longitude,londirection,altitude_km,velocity_kms
0,2022-01-11,03:33:13,126.4,2.9,58.4,S,160.2,W,40.8,22.8
1,2022-01-01,20:23:04,14.5,0.42,66.1,N,152.6,W,35.5,None
2,2021-12-29,03:15:35,2.0,0.073,69.7,S,115.0,E,44,22.0
3,2021-12-23,21:27:58,2.1,0.076,4.9,S,29.6,W,37,None
4,2021-12-20,23:15:55,3.2,0.11,62.7,N,60.3,E,56,18.2
5,2021-12-10,01:19:06,5.0,0.16,47.5,S,172.6,E,27.5,None
6,2021-11-28,18:06:50,4.0,0.13,32.6,N,113.5,E,38.4,19.7
7,2021-11-17,15:53:21,2.4,0.086,6.8,S,119.1,E,35.0,23.0
8,2021-11-08,05:28:28,3.3,0.11,33.8,S,7.7,W,36,None
9,2021-10-28,09:10:30,3.0,0.1,4.1,S,138.7,W,35.2,None
10,2021-10-21,10:32:02,3.7,0.13,51.5,N,51.4,E,30,15.9
11,2021-10-20,08:41:50,6.0,0.19,13.8,N,140.4,W,28,None
12,2021-10-20,00:43:57,2.0,0.073,59.0,N,154.3,E,31.4,27.5
13,2021-09-29,10:50:59,13.7,0.4,53.9,N,148.0,W,28.0,21.2
14,2021-09-06,17:55:42,3.1,0.11,2.1,S,111.8,W,26.0,13.6
15,2021-07-30,08:06:34,14.6,0.42,7.8,S,90.1,E,63.0,None
16,2021-07-29,13:19:57,3.7,0.13,42.4,N,98.4,E,26.4,14.7
17,2021-07-05,03:46:24,74,1.8,44.3,N,164.2,W,43.4,15.7
18,2021-05-16,15:51:08,3.8,0.13,52.1,S,171.2,W,37.0,None
19,2021-05-06,05:54:27,2.1,0.076,34.7,S,141.0,E,31.0,26.6
20,2021-04-13,02:16:47,2.1,0.076,26.8,N,79.1,W,44.4,14.1
21,2021-04-02,15:52:58,13.7,0.4,71.2,N,106.7,E,40.0,None
22,2021-03-06,08:43:06,14.1,0.41,48.6,S,90.4,E,31.1,None
23,2021-03-05,13:50:01,3.9,0.13,81.1,S,141.1,E,32.5,None
24,2021-02-09,23:27:29,3.0,0.1,75.8,N,92.8,W,31.0,None
25,2021-02-02,10:03:21,3.1,0.11,48.7,N,80.1,E,20,None
26,2021-01-31,02:59:39,26.7,0.72,5.3,N,115.2,E,39.4,None
27,2021-01-29,16:12:47,7.7,0.24,38.8,N,51.3,W,30.0,None
28,2021-01-25,03:01:37,7.5,0.23,38.5,N,47.6,W,19.1,None
29,2021-01-24,07:33:43,6.1,0.2,45.0,S,95.5,E,37.5,None

fire_ball_data
del fire_ball_data['time']
del

## pushing data to sql/postgress

In [12]:
engine = create_engine('sqlite:///cad.sqlite', echo=True)
sqlite_connection = engine.connect()

In [13]:
Base = declarative_base()

In [14]:
# Build class for the database
class Fireball_data(Base):
    __tablename__ = "fireball_data"
    date = Column(String, primary_key = True)
    time = Column (String, primary_key = True)
    energy = Column (Integer)
    impactenergy = Column (Integer)
    latitude = Column (Integer)
    latdirection = Column (String)
    longitude = Column (Integer)
    londirection = Column (String)   
    altitude_km = Column (Integer)
    velocity_kms = Column (Integer)

In [15]:
sqlite_table = "fireball_data"
fire_ball_data.to_sql(sqlite_table, sqlite_connection, if_exists='fail')

2022-01-19 19:36:58,048 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("fireball_data")
2022-01-19 19:36:58,049 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-01-19 19:36:58,052 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("fireball_data")
2022-01-19 19:36:58,057 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-01-19 19:36:58,065 INFO sqlalchemy.engine.Engine
CREATE TABLE fireball_data (
	"index" BIGINT,
	date DATE,
	time TIME,
	energy TEXT,
	impactenergy TEXT,
	latitude TEXT,
	latdirection TEXT,
	longitude TEXT,
	londirection TEXT,
	altitude_km TEXT,
	velocity_kms TEXT
)


2022-01-19 19:36:58,069 INFO sqlalchemy.engine.Engine [no key 0.00382s] ()
2022-01-19 19:36:58,668 INFO sqlalchemy.engine.Engine COMMIT
2022-01-19 19:36:58,670 INFO sqlalchemy.engine.Engine CREATE INDEX ix_fireball_data_index ON fireball_data ("index")
2022-01-19 19:36:58,672 INFO sqlalchemy.engine.Engine [no key 0.00154s] ()
2022-01-19 19:36:58,841 INFO sqlalchemy.engine.Engine COMMIT
2022-01-19 19:36:58,860 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-01-19 19:36:58,877 INFO sqlalchemy.engine.Engine INSERT INTO fireball_data ("index", date, time, energy, impactenergy, latitude, latdirection, longitude, londirection, altitude_km, velocity_kms) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2022-01-19 19:36:58,895 INFO sqlalchemy.engine.Engine [generated in 0.02401s] ((0, '2022-01-11', '03:33:13.000000', '126.4', '2.9', '58.4', 'S', '160.2', 'W', '40.8', '22.8'), (1, '2022-01-01', '20:23:04.000000', '14.5', '0.42', '66.1', 'N', '152.6', 'W', '35.5', None), (2, '2021-12-29', '03:15:35.000000', '2.0', '0.073', '69.7', 'S', '115.0', 'E', '44', '22.0'), (3, '2021-12-23', '21:27:58.000000', '2.1', '0.076', '4.9', 'S', '29.6', 'W', '37', None), (4, '2021-12-20', '23:15:55.000000', '3.2', '0.11', '62.7', 'N', '60.3', 'E', '56', '18.2'), (5, '2021-12-10', '01:19:06.000000', '5.0', '0.16', '47.5', 'S', '172.6', 'E', '27.5', None), (6, '2021-11-28', '18:06:50.000000', '4.0', '0.13', '32.6', 'N', '113.5', 'E', '38.4', '19.7'), (7, '2021-11-17', '15:53:21.000000', '2.4', '0.086', '6.8', 'S', '119.1', 'E', '35.0', '23.0')  ... displaying 10 of 30 total bound parameter sets ...  (28, '2021-01-25', '03:01:37.000000', '7.5', '0.23', '38.5', 'N', '47.6', 'W', '19.1', None), (29, '2021-01-24', '07:33:43.000000', '6.1', '0.2', '45.0', 'S', '95.5', 'E', '37.5', None))
2022-01-19 19:36:58,917 INFO sqlalchemy.engine.Engine COMMIT

In [16]:
sqlite_connection.close()

In [17]:
# # rds_connection_string = "postgres:Korudo7$@localhost:5432/cad"
# rds_connection_string = "postgres:postgres@localhost:5050/cad"
# engine = create_engine(f'postgresql://{rds_connection_string}')

In [18]:
# engine.table_names()

In [19]:
# fire_ball_data.to_sql(name='fire_ball_data', con=engine, if_exists='append', index=False)